[package]
name = "coap"
version = "0.2.2"
description = "A CoAP library"
readme = "README.md"
documentation = "http://covertness.github.io/coap-rs/coap/index.html"
repository = "https://github.com/covertness/coap-rs"
license = "MIT"
authors = ["Yang Zhang <wuyingfengsui@gmail.com>"]
keywords = ["CoAP"]

[dependencies]
bincode = "0.3.0"
rustc-serialize = "0.3"
bytes = "0.2.11"
mio = "0.4"
threadpool = "0.1"
url = "0.2.36"
num = "0.1"
rand = "0.3"

[dev-dependencies]
quickcheck = "*"