[package]
name = "coap"
version = "0.7.3"
description = "A CoAP library"
readme = "README.md"
documentation = "http://covertness.github.io/coap-rs/master/coap/index.html"
repository = "https://github.com/covertness/coap-rs"
license = "MIT"
authors = ["Yang Zhang <wuyingfengsui@gmail.com>"]
keywords = ["CoAP"]

[dependencies]
bincode = "0.3.0"
rustc-serialize = "0.3"
mio = "0.5"
url = "1.7.1"
num = "0.1"
rand = "0.3"
log = "0.3"
threadpool = "1.3"
enum_primitive = "0.1.1"
regex = "1.0.2"

[dev-dependencies]
quickcheck = "0.2.27"
