[package]
name = "coap"
version = "0.8.0"
description = "A CoAP library"
readme = "README.md"
documentation = "http://covertness.github.io/coap-rs/master/coap/index.html"
repository = "https://github.com/covertness/coap-rs"
license = "MIT"
authors = ["Yang Zhang <wuyingfengsui@gmail.com>"]
keywords = ["CoAP"]
edition = "2018"

[dependencies]
bincode = "1.1.2"
serde = { version= "1.0.88", features= [ "derive" ] }
url = "1.7.2"
num-derive = "0.2.4"
num-traits = "0.2.6"
log = "0.4.6"
regex = "1.1.0"
tokio = "0.2.0-alpha.2"
tokio-net = "0.2.0-alpha.2"
futures-preview = { version = "=0.3.0-alpha.18", features = ["nightly", "async-await"] }
bytes = "0.4.12"

[dev-dependencies]
quickcheck = "0.8.2"
